<a href="https://colab.research.google.com/github/khushwantsanwalot/CompVis/blob/main/Tensor's.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

Tensors are Multidimensional Array

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([1,3,4],dtype=tf.float64)
print(tensor_one_d)

tf.Tensor([1. 3. 4.], shape=(3,), dtype=float64)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,4],
    [5,3,2],
    [6,3,6]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [5 3 2]
 [6 3 6]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([[
    [2,4,5],[6,4,3],
]])
print(tensor_three_d)

tf.Tensor(
[[[2 4 5]
  [6 4 3]]], shape=(1, 2, 3), dtype=int32)


In [ ]:
tensor_three_d.ndim

3

In [ ]:
tensor_four_d = tf.constant([[[
    [2,3,5,6],[7,4,2,5]
],[
    [2,4,5,6],[5,7,4,2]
]]])
print(tensor_four_d)

tf.Tensor(
[[[[2 3 5 6]
   [7 4 2 5]]

  [[2 4 5 6]
   [5 7 4 2]]]], shape=(1, 2, 2, 4), dtype=int32)


In [ ]:
tensor_four_d.ndim

4