<a href="https://colab.research.google.com/github/khushwantsanwalot/CompVis/blob/main/Tensor's.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

Tensors are Multidimensional Array

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([1,3,4],dtype=tf.float64)
print(tensor_one_d)

tf.Tensor([1. 3. 4.], shape=(3,), dtype=float64)


In [4]:
tensor_two_d = tf.constant([
    [1,2,4],
    [5,3,2],
    [6,3,6]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 4]
 [5 3 2]
 [6 3 6]], shape=(3, 3), dtype=int32)


In [5]:
tensor_three_d = tf.constant([[
    [2,4,5],[6,4,3],
]])
print(tensor_three_d)

tf.Tensor(
[[[2 4 5]
  [6 4 3]]], shape=(1, 2, 3), dtype=int32)


In [6]:
tensor_three_d.ndim

3

In [7]:
tensor_four_d = tf.constant([[[
    [2,3,5,6],[7,4,2,5]
],[
    [2,4,5,6],[5,7,4,2]
]]])
print(tensor_four_d)

tf.Tensor(
[[[[2 3 5 6]
   [7 4 2 5]]

  [[2 4 5 6]
   [5 7 4 2]]]], shape=(1, 2, 2, 4), dtype=int32)


In [8]:
tensor_four_d.ndim

4

In [9]:
tensor_one_d = tf.constant([1,3,4],dtype=tf.int32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([1 3 4], shape=(3,), dtype=int32)
tf.Tensor([1 3 4], shape=(3,), dtype=int16)


In [10]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [13]:
tensor_string = tf.constant(['Hello World','hi'])
print(tensor_string)

tf.Tensor([b'Hello World' b'hi'], shape=(2,), dtype=string)


In [14]:
import numpy as np

In [15]:
np_array = np.array([1,3,4])
print(np_array)

[1 3 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)